name: Build ppc64le

on:
  push:
    branches: [ main ]
   
jobs:
  build-main:
    name: Build and push a ppc64le snapshot image
    runs-on: ubuntu-latest
    env:
      IMAGE_REGISTRY: quay.io/opdev
    steps:
    - uses: actions/checkout@v2
    - name: Fetch latest release version
      uses: reloc8/action-latest-release-version@1.0.0
      id: fetch-latest-release
    - name: Set Env Tags
      run: echo RELEASE_TAG=${{ steps.fetch-latest-release.outputs.latest-release }} >> $GITHUB_ENV
    
    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
        
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_REGISTRY }}/preflight
        tags: ppc64le ${{ github.sha }}
        archs: ppc64le
        build-args: |
          quay_expiration=1w
          release_tag=${{ env.RELEASE_TAG }}-alpha+${{ github.sha }}
          ARCH=ppc64le
        dockerfiles: |
          ./Dockerfile
          
    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: preflight
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
